workflows:
  android-build:
    name: Build Exo Stream Player
    max_build_duration: 60
    instance_type: linux
    environment:
      vars:
        BUILD_DIR: "app/build/outputs/apk/release"
      java: 17
    scripts:
      - name: Set Gradle permissions
        script: chmod +x ./gradlew
      - name: Accept Android SDK licenses
        script: yes | sdkmanager --licenses
      - name: Build Release APK
        script: ./gradlew assembleRelease
    artifacts:
      - $BUILD_DIR/*.apk
